const flights = [
  {
    image: "../assets/Red Planet Ventures/Assets/Images/flighhtMars.png",
    title: "The Classic Mars Experience",
    currentPrice: 25000.00,
    originalPrice: 50000.00,
    rating: 4,
    reviews: 36,
    description: "Embark on a Mars vacation: red deserts, ancient relics, and towering canyons await. Enjoy low-gravity hiking, rover trips to Olympus Mons, and stargazing under Phobos and Deimos. Unforgettable adventures beckon on the rust-colored landscapes of the Red Planet.",
    quantity: 1,
    sku: "SS001",
    shuttle: "The Opulence",
    tags: ["Mars", "Luxury", "Sale"],
    fromDate: new Date("2024-06-16"),
    toDate: new Date("2024-07-10")
  },
  {
    image: "../assets/Red Planet Ventures/Assets/Images/flightNeptune.png",
    title: "Neptune's Cosmic Dive",
    currentPrice: 45000.00,
    originalPrice: "",
    rating: 4,
    reviews: 24,
    description: "Embark on a voyage to Neptune's abroad the \"Neptune Voyager\". Witness surreal vistas of swirling clouds and rings. Explore weightlessness and frigid oceans. Engage in thrilling spacewalks, observe celestial phenomena, and savor gourmet space cuisine. An unforgettable adventure awaits, blending luxury with cosmic exploration.",
    quantity: 1,
    sku: "SS405",
    shuttle: "The Voyager",
    tags: ["Neptune", "Commercial", "Gourmet Experience"],
    fromDate: new Date("2024-04-04"),
    toDate: new Date("2024-03-28")
  },
  {
    image: "../assets/Red Planet Ventures/Assets/Images/flightJupiter.png",
    title: "The Giant's Journey",
    currentPrice: 65000.00,
    originalPrice: "",
    rating: 5,
    reviews: 16,
    description: "Embark on a Jupiter voyage aboard the \"Jupiter Odyssey\". Witness its majestic storms and swirling atmosphere. Dive into metallic hydrogen oceans. Explore its moons, each a world unto itself. Engage in gravity surfing, comet chasing, and space excursions. Experience cosmic wonder in luxury, blending exploration with adventure.",
    quantity: 1,
    sku: "SS606",
    shuttle: "The Odyssey",
    tags: ["Jupiter", "Luxury", "Adventure"],
    fromDate: new Date("2024-06-15"),
    toDate: new Date("2024-07-30")
  },
  {
    image: "../assets/Red Planet Ventures/Assets/Images/flightSaturn.png",
    title: "Ring Around a Saturn",
    currentPrice: 40000.00,
    originalPrice: "",
    rating: 5,
    reviews: 16,
    description: "Embark on a thrilling voyage to Saturn aboard the \"Saturn Explorer\". Marvel at its iconic rings and turbulent storms. Explore its diverse moons, from icy Enceladus to mysterious Titan, with activities including rover expeditions and cave exploration. Experience the wonders of the cosmos amidst luxurious accommodations where the thrill of discovery intertwines seamlessly with the excitement of adventure.",
    quantity: 1,
    sku: "SS333",
    shuttle: "The Explorer",
    tags: ["Saturn", "Luxury", "Adventure"],
    fromDate: new Date("2024-04-04"),
    toDate: new Date("2024-03-28")
  },
  {
    image: "../assets/Red Planet Ventures/Assets/Images/flightUranus.png",
    title: "Uranus Uncharted",
    currentPrice: 50000.00,
    originalPrice: "",
    rating: 5,
    reviews: 12,
    description: "Embark on a cosmic adventure to Uranus with our \"Uranus Unveiled\" tour. Explore its icy atmosphere and captivating moons. Experience thrilling zero-gravity excursions, witness mesmerizing auroras and immerse yourself in celestial photography workshops. With luxury accommodations and expert guides, discover the wonders of Uranus in a journey of a lifetime.",
    quantity: 1,
    sku: "SS735",
    shuttle: "The Endeavor",
    tags: ["Uranus", "Workshop", "Adventure"],
    fromDate: new Date("2024-05-16"),
    toDate: new Date("2024-07-19")
  },
  {
    image: "../assets/Red Planet Ventures/Assets/Images/flightMoon.png",
    title: "Moonlight Meander",
    currentPrice: 15000.00,
    originalPrice: "",
    rating: 4,
    reviews: 43,
    description: "Experience the ultimate lunar getaway with our \"Moonlight Meander\" package. Depart Earth's atmosphere aboard the \"Celestial Cruiser\" for a short but unforgettable journey to the moon. Enjoy lunar walks, breathtaking views of Earthrise, and stargazing under the moon's serene glow. Immerse yourself in luxury accommodations amidst the tranquility of space.",
    quantity: 1,
    sku: "SS451",
    shuttle: "The Voyager",
    tags: ["Moon", "Commercial", "Romantic"],
    fromDate: new Date("2024-08-05"),
    toDate: new Date("2024-08-12")
  }
];